imports:
    - { resource: "@SyliusMolliePlugin/Resources/config/services.xml" }
    - { resource: "@SyliusMolliePlugin/Resources/config/resources.yaml" }
    - { resource: "@SyliusMolliePlugin/Resources/config/state_machine.yaml" }
    - { resource: "@SyliusMolliePlugin/Resources/config/grids.yaml" }
    - { resource: "@SyliusMolliePlugin/Resources/config/email.yaml" }
    - { resource: "@SyliusMolliePlugin/Resources/config/ui.yaml" }

twig:
    globals:
        subscription_mollie_repository: "@sylius_mollie_plugin.repository.mollie_subscription"
