imports:
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/mollie_methods.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/payment_surcharge_fee.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/mollie_method_image.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/mollie_logger.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/mollie_customer.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/mollie_email_template.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/order.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/product_type.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/payment_method.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/onboarding_wizard_status.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/mollie_subscription.yaml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources/mollie_subscription_schedule.yaml" }
    - { resource: "@SyliusRefundPlugin/Resources/config/app/config.yml" }
