winzou_state_machine:
  sylius_order_checkout:
    callbacks:
      after:
        sylius_mollie_plugin_payment_surcharge:
          on: ["select_payment"]
          do: ["@sylius_mollie_plugin.processor.payment_surcharge_processor", "process"]
          args: ["object"]
  sylius_shipment:
    transitions:
      create_and_ship:
        from: [cart]
        to: shipped
    callbacks:
      before:
        mollie_purify_empty_ready_shipments:
          on: ["ship", "create_and_ship"]
          do: ["@sylius_mollie_plugin.purifier.partial_ship.order_shipment_purifier", "purify"]
          args: ["object.getOrder()"]
      after:
        sylius_resolve_state:
          on: ["ship", "create_and_ship"]
          do: ["@sylius.state_resolver.order_shipping", "resolve"]
          args: ["object.getOrder()"]
