winzou_state_machine:
    mollie_subscription:
        class: "%sylius_mollie_plugin.model.mollie_subscription.class%"
        property_path: state
        graph: mollie_subscription_graph
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            processing: ~
            active: ~
            cancelled: ~
            suspended: ~
            completed: ~
            aborted: ~
        transitions:
            process:
                from: [new, active, suspended, completed]
                to: processing
            activate:
                from: [new, processing, suspended, completed]
                to: active
            cancel:
                from: [processing, active, suspended, completed]
                to: cancelled
            suspend:
                from: [new, processing, active, completed]
                to: suspended
            complete:
                from: [new, processing, active, suspended]
                to: completed
            abort:
                from: [new, processing, active, suspended, completed]
                to: aborted
        callbacks:
            guard:
                sylius_mollie_plugin_activate_recurring_subscription_guard_for_complete:
                    on: 'complete'
                    do: [ '@sylius_mollie_plugin.guard.subscription', 'isCompletable' ]
                    args: [ 'object' ]
                sylius_mollie_plugin_activate_recurring_subscription_guard_for_abort:
                    on: 'abort'
                    do: [ '@sylius_mollie_plugin.guard.subscription', 'isEligibleForPaymentsAbort' ]
                    args: [ 'object' ]
            after:
                sylius_mollie_plugin_activate_recurring_subscription_process:
                    on: ["activate"]
                    do: ["@sylius_mollie_plugin.processor.subscription_schedule_processor", "processScheduleGeneration"]
                    args: ["object"]

    mollie_subscription_processing:
        class: "%sylius_mollie_plugin.model.mollie_subscription.class%"
        property_path: processingState
        graph: mollie_subscription_processing_graph
        state_machine_class: "%sylius.state_machine.class%"
        states:
            none: ~
            pending: ~
            processing: ~
        transitions:
            process:
                from: [none, pending]
                to: processing
            schedule:
                from: [processing, none]
                to: pending
