sylius_mollie_plugin_mollie_logger:
  resource: |
    alias: sylius_mollie_plugin.mollie_logger
    section: admin
    path: /mollie/logger
    permission: true
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: sylius_mollie_plugin_mollie_logger
    vars:
        all:
            subheader: sylius_mollie_plugin.ui.logger_list
        index:
            icon: 'tags'
  type: sylius.resource
