bitbag_sylius_mollie_plugin_mollie_logger:
  resource: |
    alias: bitbag_sylius_mollie_plugin.mollie_logger
    section: admin
    path: /mollie/logger
    permission: true
    templates: SyliusAdminBundle:Crud
    redirect: update
    grid: bitbag_sylius_mollie_plugin_mollie_logger
    vars:
        all:
            subheader: bitbag_sylius_mollie_plugin.ui.logger_list
        index:
            icon: 'tags'
  type: sylius.resource
