app_admin_product_type:
    resource: |
        alias: sylius_mollie_plugin.product_type
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        grid: sylius_mollie_plugin_admin_product_type
        redirect: index
        permission: true
    type: sylius.resource
